---
title: "Untitled"
author: "Alla Tambovtseva"
date: "27 11 2020"
output: pdf_document
---

## Задачи

### Задача 1

Загрузите в R данные из файла `sleep.csv`, сохраните их в датафрейм `sleep_surv`. При загрузке сделайте так, чтобы все текстовые столбцы считались как факторные.

### Задача 2

Выведите на экран уровни показателя `marital`. 

### Задача 3

Измените уровни показателя `marital` таким образом, чтобы они были упорядочены в соответствии с перечнем значений, представленным в описании данных.

### Задача 4

Выведите на экран частоты значений в столбце `edlevel`. 

**Подсказка.** Функция `table()`. 

### Задача 5

Измените уровни показателя `edlevel` так, чтобы они были упорядочены в соответствии с перечнем значений, представленным в описании данных. Выведите на экран частоты значений в столбце `edlevel`. Чем отличается результат этой операции от результата задачи 4? Приведите ответ на вопрос.

### Задача 6

Сделайте показатель `qualslp` упорядоченным фактором, считая, что значения должны быть упорядочены от самого худшего к самому лучшему.

### Задача 7

Выберите из датафрейма `sleep_surv` строки, соответствующие курящим людям. Сохраните их в датафрейм `sleep_smoke`. 

### Задача 8

Используя датафрейм `sleep_smoke`, определите, чему равны минимальное и максимальное значения показателя качества сна. Выясните, какое из значений качества сна у курящих людей встречается чаще всего. 

### Задача 9

Используя возможности `tidyverse`, сделайте так, чтобы значения с частотой ниже 30 в столбце `marital` были закодированы с помощью слова other. Проверьте, какие значения превратились в other, и запишите свой ответ.

### Задача 10 

Сделайте столбец smoke целочисленным так, чтобы значение 0 соответствовало некурящим людям, а 1 — курящим людям. 

### Задача 11 

Выгрузите обновлённый датафрейм `sleep_surv` в файл `sleep-new.csv`. 
