---
title: "Домашнее задание"
output: html_document
---

## Задачи 

### Задача 1

Загрузите данные из файла `Cowles.csv` и сохраните их в датафрейм `psy`. 

### Задача 2

Выведите описательные статистики по всем столбцам датафрейма `psy`. Проинтерпретируйте полученную выдачу.

### Задача 3

Используя библиотеку `ggplot2`, постройте гистограмму для уровня экстраверсии по шкале Айзенка. Сделайте шаг гистограммы равным стандартному отклонению визуализируемого показателя. Измените цвет заливки гистограммы, цвет границ столбцов. Добавьте содержательные подписи по осям и заголовок графика.

Проинтерпретируйте полученный график: сформулируйте, что можно сказать о форме распределения (симметричное, скошенное) и о самых распространённых значениях показателя.

**Подсказка:** стандартное отклонение показателя можно получить с помощью базовой функции `sd()`. 

### Задача 4

Используя библиотеку `ggplot2`, постройте графики плотности распределения для уровня невротизма с группировкой по полу респондента. Оба графика должны находиться в пределах одной картинки. Настройте прозрачность графиков, измените цвета заливки. Измените подписи в легенде таким образом, чтобы они были на русском языке.

Проинтерпретируйте полученный график: укажите, у кого в целом уровень невротизма выше, у мужчин или женщин.  

### Задача 5

Используя библиотеку `ggplot2`, постройте гистограммы для уровня экстраверсии с группировкой по индикатору участия в волонтёрских мероприятиях. Оба графика должны находиться в разных окнах-фасетках в пределах одной картинки. Сделайте шаг гистограмм равным двум. Измените цвета заливки так, чтобы графики были разного цвета. Измените все подписи на графике таким образом, чтобы они были на русском языке.

### Задача 6

Используя библиотеку `ggplot2`, постройте столбчатую диаграмму, которая показывает, сколько респондентов мужского и женского пола принимало участие в опросе. Измените цвета заливки столбцов, выбрав цветовую палитру R по своему усмотрению.

Проинтерпретируйте полученный график: укажите, кого больше среди респондентов, мужчин или женщин.

### Задача 7

Используя библиотеку `ggplot2`, постройте круговую диаграмму, которая показывает, какая доля респондентов принимает участие в волонтёрских мероприятиях. Измените цвета заливки секторов, выбрав цветовую палитру R по своему усмотрению.

Проинтерпретируйте полученный график: укажите, кого больше среди респондентов, волонтёров или неволонтёров.

### Задача 8

Загрузите данные из файла `Crimes.csv` и сохраните их в датафрейм `crimes`. 

### Задача 9

Используя возможности библиотеки `tidyverse`, сохраните в датафрейм `states_an` строки, соответствующие штатам Калифорния, Флорида, Айова (California, Florida, Iowa). 

### Задача 10

Используя библиотеку `ggplot2` и данные из датафрейма `states_an`, постройте линейные графики, которые отражают динамику числа краж по годам в штатах Калифорния, Флорида и Айова. Сделайте так, чтобы линии, соответствующие разным штатам, имели разные начертания (сплошная линия, пунктирная линия и так далее).

### Задача 11

Используя библиотеку `ggplot2` и данные из датафрейма `crimes`, постройте диаграмму рассеивания, которая отражает связь между числом краж и числом заключённых в тюрьму. 

Проинтерпретируйте полученный график: можно ли считать, что чем больше число заключённых в тюрьму, тем меньше краж?
