---
title: "Домашнее задание"
output: pdf_document
header-includes:
  -  \usepackage[russian]{babel}
  -  \usepackage{hyperref}
  -  \usepackage{amsmath}
  -  \hypersetup{colorlinks=true,urlcolor=blue}
---

## Задача 1

Ниже приведено описание показателей, взятых из документации к результатам опроса:

* `ID`: id респондента, целочисленный тип;
* `GENDER`: пол, факторный тип (значения: 1 — женский, 2 — мужской);
* `YEAR`: год рождения, целочисленный тип.

Даны векторы, в которых сохранены несколько случайно выбранных значений из показателей, описанных выше:

```{r}
ID <- 100:108
GENDER <- c(1, 2, 2, 1, 2, 1, 1, 1)
YEAR <- c("1983", " 1988", "1975 ", "1980", "1977  ", "1992", "1994", "1983 ")
```

**1.1.** Проверьте, к какому типу относятся векторы (числовой, целочисленный, логический, строковый, факторный). 



**1.2.** Если тип какого-то вектора не соответствует заявленному в описании выше, исправьте это, сохранив изменения в самом векторе. Среди приведённых выше векторов «неправильных» может быть несколько.

## Задача 2

В таблицах ниже приведены данные по объёму экспорта и импорта товаров в долларах США за 2019 год для трёх стран (данные проекта [COMTRADE](https://comtrade.un.org/)).

\begin{table}[ht!]
\centering
\caption{экспорт}
\begin{tabular}{|c|c|c|}
\hline
\textbf{Партнёр 1} & \textbf{Партнёр 2} & \textbf{Экспорт (доллары США)} \\
\hline
Канада & Нидерланды & 3 905 228 446\\
\hline
Канада & США & 336 531 873 909 \\
\hline
Нидерланды & Канада & 4 862 948 109 \\
\hline
Нидерланды & США & 29 807 484 356 \\
\hline
США & Канада & 292 338 433 401 \\
\hline
США & Нидерланды & 51 225 636 600\\
\hline
\end{tabular}
\end{table}

\begin{table}[ht!]
\centering
\caption{импорт}
\begin{tabular}{|c|c|c|}
\hline
\textbf{Партнёр 1} & \textbf{Партнёр 2} & \textbf{Импорт (доллары США)} \\
\hline
Канада & Нидерланды & 3 515 239 399\\
\hline
Канада & США & 229 687 088 046 \\
\hline
Нидерланды & Канада & 2 249 551 077 \\
\hline
Нидерланды & США & 42 262 861 193 \\
\hline
США & Канада & 326 628 559 104 \\
\hline
США & Нидерланды & 30 883 263 358\\
\hline
\end{tabular}
\end{table}

**2.1.** Создайте датафреймы `goods_export` и `goods_import`, которые выглядят так, как таблицы с данными выше. 

**Подсказка:** названия столбцов датафрейма добавляются с помощью той же функции, что и у матриц.

**2.2.** На основе данных из таблиц 1 и 2 создайте матрицы `export_mat` и `import_mat`, которые будут в более компактном виде хранить информацию об экспорте и импорте. Это должны быть квадратные матрицы (число строк равно числу столбцов), по строкам и столбцам должны идти названия стран: Канада, Нидерланды, США.

**Пример.** Известно, что страна A экспортирует в страну B товара на 20 000 долларов, а B экспортирует в А товара на 40 000 долларов. При этом мы считаем, что сама страна в себя ничего не экспортирует. Создадим матрицу для описания экспорта двух стран A и B:

\begin{table}[ht!]
\centering
\begin{tabular}{cc}
\textbf{A} & \textbf{B} \\
0 & 20000 \\
40000 & 0 \\
\end{tabular}
\end{table}

**2.3.** Используя матрицы из пункта 2.2, создайте матрицу `diff_mat`, которая содержит разницу между экспортом и импортом стран.

**2.4.** Используя матрицы из пункта 2.2, создайте матрицы с логарифмированными (десятичный логарифм) значениями экспорта и импорта. Назовите матрицы по своему усмотрению.

**2.5.** Создайте список `L_data`, который содержит следующие элементы:

* элемент `source` со значением "COMTRADE, https://comtrade.un.org/";
* элемент `year` со значением "2019";
* элемент `countries` — вектор с названиями стран (как в матрицах);
* элемент `export` — датафрейм `goods_export`;
* элемент `import` — датафрейм `goods_import`;
* элемент `export_mat` — матрица `export_mat`;
* элемент `import_mat` — матрица `export_mat`.

**2.6.** Используя созданный список `L_data` и обращаясь только к индексам элементов, выведите на экран:

* третью страну в векторе `countries`;
* объём экспорта из Нидерландов в Канаду из матрицы `export_mat`;
* объём импорта из США в Канаду из матрицы `import_mat`.

**2.7.** Добавьте в конец списка `L_data` элемент без названия, который содержит строку с сегодняшней датой в произвольном формате.
