---
title: "Домашнее задание"
output: html_document
---

# Задачи

## Задача 1

Загрузите данные из файла `travel-times.csv` и сохраните их в датафрейм `travel`.

## Задача 2

Удалите из датафрейма `travel` столбец `Comments`.

## Задача 3

Замените в датафрейме `travel` все значения `""` и `"-"` на `NA`.

**Подсказка.** Пример кода для замены значения 99 на `NA`:

```
dat[dat == 99] <- NA
```

## Задача 4

Посчитайте количество ячеек с пропущенными значениями в датафрейме `travel`. Посчитайте количество строк, содержащих пропущенные значения, в датафрейме `travel`. Сравните результаты. Можно ли считать, что каждая строка содержит ровно одно пропущенное значение? Приведите ответ на вопрос в файле с домашним заданием.

## Задача 5

Используя библиотеку `VIM`, постройте две визуализации для выявления закономерностей в пропущенных значениях. Проинтерпретируйте полученные результаты: определите, в каких столбцах встречаются пропущенные значения, поясните, наблюдаются ли какие-то закономерности в пропущенных значениях. Предложите возможные причины появления пропусков в данных. Приведите ответы на вопросы в файле с домашним заданием.

## Задача 6

Вычислите среднее и медианное значение по столбцам, в которых встречаются пропущенные значения. Если среднее значение сильно отличается от медианного, заполните пропуски медианным значением по столбцу, если нет — средним значением по столбцу.

## Задача 7

Загрузите данные из файла `melb_data.csv` и сохраните их в датафрейм `melb`.

## Задача 8

Используя библиотеку `VIM`, постройте две визуализации для выявления закономерностей в пропущенных значениях. Проинтерпретируйте полученные результаты: определите, в каких столбцах встречаются пропущенные значения, поясните, наблюдаются ли какие-то закономерности в пропущенных значениях. Предложите возможные причины появления пропусков в данных. Приведите ответы на вопросы в файле с домашним заданием.

## Задача 9

Заполните пропущенные значения в столбце `Car` с помощью метода, который берёт значение из ячейки над ячейкой с пропуском.

## Задача 10

Заполните пропущенные значения в столбце `BuildingArea` средним значением по столбцу.

## Задача 11

Заполните пропущенные значения в столбце `YearBuilt` медианным значением по столбцу.
