---
title: "Домашнее задание"
output:
  pdf_document:
    latex_engine: xelatex
mainfont: CMU Serif
header-includes:
- \usepackage[russian]{babel}
- \usepackage{hyperref}
- \hypersetup{colorlinks = true, urlcolor = blue, linkcolor=magenta}
---

# Задачи

*Операции в задачах 2–10 должны быть выполнены с помощью функций из системы библиотек `tidyverse`.*

## Задача 1

Загрузите данные из файла `beasts.csv` в R в датафрейм `beasts`. При необходимости выберите подходящий разделитель столбцов и десятичный разделитель. Проверьте, что все столбцы имеют корректные типы, запросив структуру датафрейма.

## Задача 2

Добавьте в датафрейм beasts столбец `Dragon`, состоящий из 0 и 1, где 1 соответствует драконам (значение `Dragon` в `Class`).

## Задача 3

Добавьте в датафрейм beasts столбец `LogSize`, содержащий натуральные логарифмы размера зверя.

## Задача 4

Добавьте в датафрейм `beasts` столбец `Danger` со следующими значениями:

* `High`: если класс Министерства Магии равен 4 или 5 (`XXXX` или `XXXXX`);
* `Medium`: если класс Министерства Магии равен 3 (`XXX`);
* `Low`: если класс Министерства Магии равен 1 или 2 (`X` и `XX`).

**Подсказка.** Можно несколько раз применить функцию `ifelse()` или написать свою функцию для преобразований.

## Задача 5

Добавьте в датафрейм `beasts` столбец `DangerNum` с числовым значением класса Министерства Магии (`X` — 1, `XX` — 2 и так далее до `XXXXX`).

**Подсказка.** Для определения длины строки может пригодиться базовая функция `nchar()`.

## Задача 6

Выберите строки, соответствующие драконам, и сохраните эти строки в датафрейм `dragons`.

## Задача 7

Выберите строки, соответствующие существам с классом Министерства Магии не ниже 4 и имеющим жёлтые глаза (`Yellow`). Сохраните эти строки в датафрейм `dang_yellow`.

## Задача 8

Выберите строки, соответствующие существам, родиной которых считается Америка (North America, South America) или Европа (Europe). Сохраните их в датафрейм `AmEu`.

**Пояснение.** Это означает, что слова *North America*, *South America* и *Europe* должны присутствовать в ячейке в столбце `Native`, в том числе в составе перечня стран. Например, в `AmEu` должны уйти существа со значениями `Europe`, `Europe|North America`, `Europe|Russia|North America|South America` и подобные.

## Задача 9

Сгруппируйте строки по значениям столбца `Eye` и выведите для каждой группы число существ в каждой группе, а также долю таких существ от общего числа существ в датафрейме.

## Задача 10

Сгруппируйте строки по значениям столбца `Classification` и выведите для каждой группы минимальный, средний и максимальный размер существа.

## Задача 11

С помощью библиотеки `stargazer` сформируйте выдачу, совпадающую по содержанию с таблицей из задачи 10. Выгрузите полученную выдачу в файл с расширением `.htm`. К выгруженной в файл таблице добавьте заголовок *Fantastic beasts*. 
