---
title: "Домашнее задание"
output: word_document
---

В файле `vgsales.csv` сохранены данные по продажам видео-игр, собранные с сайта [vgchartz.com](http://www.vgchartz.com/). 

## Показатели в файле

* `Rank`: ранг продажи;
* `Name`: название игры;
* `Platform`: платформа, для которой предназначена игра (PC, PS4, и. т. д.);
* `Year`: год выпуска игры;
* `Genre` - жанр игры;
* `Publisher` - компания, выпустившая игру;
* `NA_Sales` - число продаж в Северной Америке (в миллионах);
* `EU_Sales` - число продаж в Европе (в миллионах);
* `JP_Sales` - число продаж в Японии (в миллионах);
* `Other_Sales` - число продаж в остальных частях света/странах (в миллионах);
* `Global_Sales` - общее число продаж.

Подробнее про данные можно почитать на [странице](https://www.kaggle.com/gregorut/videogamesales) файла на Kaggle.

### Задача 1

Загрузите данные из файла `vgsales.csv` и сохраните их в датафрейм `games`.

### Задача 2

Оставьте в датафрейме `games` только строки, которые соответствуют видео-играм с общим числом продаж не более 5 миллионов. 

### Задача 3

Постройте гистограмму для показателя «общее число продаж», используя обновлённый датафрейм `games`. Измените цвет заливки гистограммы и цвет границ столбцов. Добавьте содержательные подписи на русском языке по осям `x` и `y`. Добавьте заголовок графика. 

### Задача 4

Проинтерпретируйте полученную в задаче 3 гистограмму. В интерпретации укажите форму распределения (является ли оно симметричным или скошенным, если скошенным, то в какую сторону) и напишите, какие значения встречаются чаще, а какие реже. 

### Задача 5

Добавьте на гистограмму из задачи 3 вертикальные линии, отчерчивающие среднее и медианное значение показателя соответственно. Линии должны быть разного цвета и начертания (сплошная линия, пунктирная, точечная, и так далее). Что можно сказать о различии между средним значением и медианным значением?

### Задача 6

Приведите ответ на следующий вопрос. В каких случаях использование различных начертаний линий может быть более рациональным, чем использование различных цветов?

### Задача 7

Постройте гистограммму для показателя «число продаж в Европе». Можно ли сказать, что распределение показателей «число продаж в Европе» и «общее число продаж» схожи? Приведите ответ на вопрос и обоснуйте свой ответ.

### Задача 8

Постройте столбчатую диаграмму для показателя «платформа, для которой предназначена игра». При необходимости выполните поворот подписей к столбцам. Какая платформа является наиболее популярной? Приведите ответ на вопрос.

### Задача 9

Измените цвета столбцов диаграммы из задачи 8 таким образом, чтобы последовательность из пяти разных цветов повторялась необходимое число раз (по числу столбцов). Добавьте название графика на русском языке.

### Задача 10

Скорректируйте вертикальную ось диаграммы из задачи 8 таким образом, чтобы максимальное указанное значение превышало высоту самого высокого столбца.  

### Задача 11

Постройте круговую диаграмму для показателя «». Измените цвета диаграммы таким образом, чтобы каждому жанру соответствовал уникальный цвет. Скорректируйте диаграмму таким образом, чтобы на самой диаграмме были указаны частоты в процентах, а в легенде графика — соответствие между цветами и жанрами. При необходимости, если диаграмма по-прежнему выглядит не очень презентабельно, внесите дополнительные изменения по своему усмотрению.

### Задача 12

Постройте линейный график, который отражает динамику показателя «скорость скачивания файла в торрент-программе в мегабайтах в секунду» в течение случайно выбранной минуты. Значения этого показателя сохранены в векторе `torr_pace`. 

```{r}
torr_pace <- c(0.3, 0.6, 1.5, 1.7, 1.2, 0.8, 1.7, 1.8, 2.0, 2.5, 
               2.2, 2.7, 3.3, 3.1, 3.5, 3.0, 3.2, 3.3, 3.8, 4.0, 
               3.7, 3.9, 3.5, 3.3, 3.2, 2.8, 2.5, 2.2, 1.8, 1.5,
               1.4, 1.5, 1.2, 1.6, 1.8, 2.0, 2.2, 1.9, 1.8, 1.4,
               1.2, 1.0, 0.9, 0.8, 1.1, 1.2, 1.3, 1.0, 0.8, 0.7, 
               1.1, 1.3, 1.5, 1.7, 1.6, 1.8, 1.9, 2.0, 1.5, 1.1)
```

Отредактируйте график таким образом, чтобы по нему было удобно отслеживать изменения значений показателя (добавьте подписи, разлиновку, при необходимости сделайте деления по осям более детальными).