---
title: "Домашнее задание"
output:
  pdf_document:
    latex_engine: xelatex
mainfont: CMU Serif
header-includes:
- \usepackage[russian]{babel}
- \usepackage{hyperref}
- \hypersetup{colorlinks = true, urlcolor = blue, linkcolor=magenta}
---

# Задачи

## Задача 1

Загрузите данные с листа `Rental` файла *Texas Rental* и сохраните их в датафрейм `rental`. 

## Задача 2
Преобразуйте столбец `average_rate_per_night` таким образом, чтобы он содержал только числа без символа `$` и имел целочисленный тип. 

**Подсказка.** Если планируете избавляться от символов `$` с помощью замены, обратите внимание на то, что этот символ является специальным оператором в регулярных выражениях, поэтому его необходимо экранировать с помощью `\\`.

## Задача 3

Замените значения *Studio* в столбце `bedrooms_count` на значения 0 и преобразуйте тип этого столбца в целочисленный.

## Задача 4

Разбейте столбец `date_of_listing` на два столбца, `month_listing` и `year_listing`. Столбец `month_listing` должен содержать месяц добавления жилого объекта на Airbnb (строковый тип), а столбец `year_listing` должен содержать год добавления жилого объекта на Airbnb (целочисленный тип).

## Задача 5

Загрузите данные с листа *Texas* файла *Texas Rental* и сохраните их в датафрейм `texas`. 

## Задача 6

Проверьте тип столбца `population`. Если тип не числовой, исправьте это.

## Задача 7

Объедините датафреймы `rental` и `texas` таким образом, чтобы в итоговом датафрейме были данные по всем представленным на Airbnb жилым объектам в Техасе и для каждого жилого объекта была указана численность населения в городе, где он находится. Назовите полученный датафрейм `final`.

## Задача 8

Удалите строки с пропущенными значениями в датафрейме `final`.

## Задача 9

Выберите 10 самых крупных по численности населения городов штата Техас, используя только датафрейм `final`.

**Подсказка.** Может пригодиться функция `distinct` для выбора уникальных значений.

## Задача 10

Сгруппируйте строки в датафрейме `final` по названию города и сформируйте таблицу с минимальной и максимальной средней ценой аренды за ночь для 10 самых крупных по численности населения городов штата Техас. Сохраните результат в переменную `texas_sum`.

## Задача 11

Измените структуру таблицы `texas_sum` таким образом, чтобы в таблице было два столбца: название города и минимальная/максимальная средняя цена аренды за ночь (одно значение под другим для каждого города, *long format*).
