---
title: "Домашнее задание"
output:
  word_document: default
  pdf_document: default
---

## Описание данных

В этом задании вам предлагается поработать с файлом `flats.csv`, который содержит данные по ценам на квартиры в Москве.


Показатели в файле:

* `price`: цена квартиры, в тысячах долларов;
* `totsp`: общая площадь квартиры, в квадратных метрах;
* `livesp`: жилая площадь квартиры, в квадратных метрах;
* `kitsp`: площадь кухни, в квадратных метрах;
* `dist`: расстояние от центра, в километрах;
* `metrdist`: расстояние до метро, в минутах;
* `walk`: шаговая доступность до метро (1 — пешком до метро, 0 — на транспорте);
* `brick`: материал дома (1 — кирпичный, монолит ж/б, 0 — другой);
* `floor`: этаж (1 — этаж кроме первого и последнего, 0 — иначе).

Оригинальное описание файла можно прочитать на [странице](https://www.kaggle.com/hugoncosta/price-of-flats-in-moscow) датафрейма на платформе Kaggle. 

## Задача 1

Загрузите данные из файла `flats.csv` и сохраните их в датафрейм `flats`. Посмотрите на датафрейм — откройте его в отдельном окне RStudio.

## Задача 2

Выведите на экран первые и последние строки в датафрейме. Выведите информацию о типах столбцов в таблице («структуру» датафрейма). Проверьте, чтобы все столбцы с числовыми данными считались как числовые, а не текстовые.

## Задача 3

Выведите на экран сводные характеристики всех столбцов в датафрейме — описательные статистики. Ответьте на вопросы: наблюдаются ли серьёзные отличия в медианных и средних значениях показателей (один из признаков наличия аномальных наблюдений или выбросов)? Насколько велик разброс значений цен на квартиры, если мы сравним минимальное и максимальное значение? Есть ли в каком-нибудь показателе с содержательной точки зрения нетипичные значения (отрицательные цены и прочее)?

## Задача 4

Используя базовые средства R, добавьте в датафрейм `flats` столбец `priceru`, содержащий значения цен на квартиры в тысячах рублей. Считайте, что один доллар равен примерно 78 рублям.

## Задача 5

Сохраните максимальное значение цены на квартиру в тысячах рублей в переменную `pricemax`. Используя фильтрацию строк, выясните, какими характеристиками обладает самая дорогая (согласно имеющимся данным) квартира в Москве.

## Задача 6

Сохраните минимальное значение цены на квартиру в тысячах рублей в переменную `pricemin`. Используя фильтрацию строк, выясните, какими характеристиками обладает самая дешёвая (согласно имеющимся данным) квартира в Москве.

## Задача 7

Выберите из датафрейма `flats` строки, соответствующие квартирам, которые находятся в шаговой доступности от метро и с жилой площадью выше средней. Сохраните их в датафрейм `flats1`.

## Задача 8

Выберите из датафрейма `flats` строки, соответствующие квартирам, которые стоят либо менее 5 млн рублей, либо более 35 млн рублей. Сохраните их в датафрейм `flats2`.

## Задача 9

Добавьте в датафрейм `flats` столбец `ratio`, который содержит отношение жилой площади квартиры к её общей площади.

## Задача 10

Выберите из датафрейма `flats` строки, соответствующие квартирам со значением ratio более 0,8. Обязательно ли квартиры с большой долей жилой площади самые дорогие? Приведите код и ответ на вопрос.

## Задача 11

Выберите из датафрейма столбцы `totsp`, `livesp`, `kitsp` и сохраните их в датафрейм `space`. Переименуйте столбцы, присвоив им названия `total`, `live` и `kitchen`.


